version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: virexbooks:latest
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
